'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ParticleFX.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AboutBox400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AboutBox400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlackBar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlackBar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CamsMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CamsMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DrawMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DrawMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FatTab0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FatTab0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FatTab1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FatTab1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ForceMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ForceMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GensMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GensMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoDuplicate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoDuplicate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoLink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoLink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoRefresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoRefresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoScale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoScale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ItemBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ItemBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MainMenuhigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenuhigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MainMenuLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenuLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property msgError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msgError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property msgWaring() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msgWaring", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NextFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NextFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PreFrame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PreFrame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Scroll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Scroll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ScrollBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScrollBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ScrollDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScrollDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ScrollUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ScrollUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SrollButtonBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SrollButtonBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TimePoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimePoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WaveformBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WaveformBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
